# $Id: Makefile,v 1.1 2006/07/02 15:23:38 sem Exp $

MANDIR=		${PREFIX}/man/man

MAN1=		pkg_deinstall.1 \
		pkg_fetch.1 \
		pkg_glob.1 \
		pkg_sort.1 \
		pkgdb.1 \
		portcvsweb.1 \
		portsclean.1 \
		portsdb.1 \
		portupgrade.1 \
		portversion.1

MLINKS=		pkgdb.1		pkg_which.1 \
		portupgrade.1	portinstall.1 \
		portsdb.1	ports_glob.1

MAN5=		pkgtools.conf.5

.include <bsd.prog.mk>
