# $Id: Makefile 52 2006-01-01 06:26:59Z koma2 $

FILES=	complete.sample

FILESDIR?=	${EXAMPLESDIR}/tcsh

beforeinstall:
	mkdir -p ${FILESDIR}

.include <bsd.prog.mk>

.include "${.CURDIR}/../../Makefile.compat"
