# $Id: Makefile 52 2006-01-01 06:26:59Z koma2 $

FILES=	complete.sample

FILESDIR?=	${EXAMPLESDIR}/bash

beforeinstall:
	${MKDIR} ${DESTDIR}${FILESDIR}

.include <bsd.prog.mk>

.include "${.CURDIR}/../../Makefile.compat"
