# $Id: Makefile 52 2006-01-01 06:26:59Z koma2 $

FILES=	_pkgtools

FILESDIR?=	${PREFIX}/share/zsh/site-functions

beforeinstall:
	mkdir -p ${FILESDIR}

.include <bsd.prog.mk>

.include "${.CURDIR}/../../Makefile.compat"
